Remove comment in splice
Haddock doesn't like it and fails because it thinks it's section syntax:

```
src/Data/Avro/Deriving.hs:465:15: error:
    parse error on input ‘-- $(schemaDef' sch)’
    |
465 |       x = sch -- $(schemaDef' sch)
    |               ^^^^^^^^^^^^^^^^^^^^
```